name: Postagem

on:
  push:
    branches:
      - postagem-notas-finais

jobs:
  build-deploy:
    name: Postagem Build e Deploy
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          

      - name: Unidade de teste
        run: ./gradlew test --console=plain
  
      - name: Build da aplicação
        run: |
            ./gradlew clean --console=plain
            ./gradlew build --console=plain


