name: Postagem

on:
  push:
    branches:
      - postagem-notas-finais

jobs:
  build-deploy:
    name: Postagem Build e Deploy
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: npm install

      - name: Unidade de teste
        run: gradle test --console=plain --build-file build.gradle

      - name: Unidade de teste
        run: gradle test --console=plain --build-file build.gradle

      - name: Build da aplicação
        run: |
          gradle clean --console=plain --build-file build.gradle  # Comando para limpar o diretório de build
          gradle build --console=plain --build-file build.gradle  # Comando para construir a aplicação  

