name: Postagem

on:
  push:
    branches:
      - postagem-notas-finais

jobs:
  build-deploy:
    name: Postagem Build e Deploy
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
     
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
            node-version: '14'
        
      - name: Install dependencies
        run: npm install
      

      - name: Unidade de teste
        run: mvn -B test --file pom.xml
      
      - name: Build da aplicação
        run: |
          mvn clean
          mvn -B package --file pom.xml