name: Postagem

on:
  push:
    branches:
      - postagem-notas-finais

jobs:
  build-deploy:
    name: Postagem Build e Deploy
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 'latest'
      
      - name: Install dependencies
        run: npm install

      - name: Unidade de teste 1
        run: npm test

      - name: Unidade de teste 2
        run: mvn -B test --file build.gradle

      - name: Build da aplicação
        run: |
          mvn clean
          mvn -B package --file build.gradle


